language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
install:
  - pip install -r requirements.txt -r requirements-dev.txt
before_script: pip install .
script:
  - coverage run --source boscli setup.py test
  - coverage report -m
after_script:
  - coveralls --verbose
