language: python
python:
  - "2.7"
  - "3.3"
install: "pip install -r requirements.txt -r requirements-dev.txt --use-mirrors"
before_script: python setup.py develop
script: mamba -f progress --enable-coverage
after_success: 'coverage report --include="boscli/*","spec/*"'
